// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VacunassistBackend.Data;

#nullable disable

namespace VacunnasistBackend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221219030343_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VacunassistBackend.Entities.AppliedVaccine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AppliedDose")
                        .HasColumnType("int");

                    b.Property<int>("LocalBatchVaccineId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<bool>("Synchronized")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocalBatchVaccineId");

                    b.HasIndex("PatientId");

                    b.HasIndex("UserId");

                    b.ToTable("AppliedVaccines", (string)null);
                });

            modelBuilder.Entity("VacunassistBackend.Entities.BatchVaccine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DevelopedVaccineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OverdueQuantity")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("Synchronized")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber")
                        .IsUnique();

                    b.HasIndex("DevelopedVaccineId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("BatchVaccines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatchNumber = "PF1000001",
                            DevelopedVaccineId = 1,
                            DueDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            OverdueQuantity = 0,
                            PurchaseOrderId = 3,
                            Quantity = 800,
                            RemainingQuantity = 800,
                            Status = 0,
                            Synchronized = false
                        },
                        new
                        {
                            Id = 2,
                            BatchNumber = "PF1000121",
                            DevelopedVaccineId = 1,
                            DueDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            OverdueQuantity = 0,
                            PurchaseOrderId = 4,
                            Quantity = 400,
                            RemainingQuantity = 400,
                            Status = 0,
                            Synchronized = false
                        },
                        new
                        {
                            Id = 3,
                            BatchNumber = "R1000001",
                            DevelopedVaccineId = 2,
                            DueDate = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            OverdueQuantity = 0,
                            PurchaseOrderId = 5,
                            Quantity = 560,
                            RemainingQuantity = 560,
                            Status = 0,
                            Synchronized = false
                        },
                        new
                        {
                            Id = 4,
                            BatchNumber = "FLU12214001",
                            DevelopedVaccineId = 3,
                            DueDate = new DateTime(2022, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            OverdueQuantity = 0,
                            PurchaseOrderId = 6,
                            Quantity = 1500,
                            RemainingQuantity = 1500,
                            Status = 0,
                            Synchronized = false
                        },
                        new
                        {
                            Id = 5,
                            BatchNumber = "FLU12214003",
                            DevelopedVaccineId = 3,
                            DueDate = new DateTime(2023, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            OverdueQuantity = 0,
                            PurchaseOrderId = 7,
                            Quantity = 3600,
                            RemainingQuantity = 3000,
                            Status = 0,
                            Synchronized = false
                        },
                        new
                        {
                            Id = 6,
                            BatchNumber = "FLU13214121",
                            DevelopedVaccineId = 3,
                            DueDate = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            OverdueQuantity = 0,
                            PurchaseOrderId = 8,
                            Quantity = 3600,
                            RemainingQuantity = 3600,
                            Status = 0,
                            Synchronized = false
                        });
                });

            modelBuilder.Entity("VacunassistBackend.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("VacunassistBackend.Entities.DevelopedVaccine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DaysToDelivery")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VaccineText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DevelopedVaccines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DaysToDelivery = 30,
                            IsActive = true,
                            Name = "Pfizer",
                            VaccineText = "{\"Id\":2000,\"Name\":\"COVID-19\",\"VaccineType\":\"ARNM\",\"Type\":1,\"Doses\":[{\"Id\":2001,\"Number\":0,\"IsReinforcement\":false,\"MinMonthsOfAge\":0,\"DaysAfterPreviousDose\":null},{\"Id\":2002,\"Number\":1,\"IsReinforcement\":false,\"MinMonthsOfAge\":0,\"DaysAfterPreviousDose\":120}]}"
                        },
                        new
                        {
                            Id = 2,
                            DaysToDelivery = 60,
                            IsActive = true,
                            Name = "ROCHE",
                            VaccineText = "{\"Id\":1300,\"Name\":\"Fiebre Amarilla\",\"VaccineType\":\"subunidades proteicas\",\"Type\":0,\"Doses\":[{\"Id\":1301,\"Number\":0,\"IsReinforcement\":false,\"MinMonthsOfAge\":18,\"DaysAfterPreviousDose\":null},{\"Id\":1302,\"Number\":1,\"IsReinforcement\":true,\"MinMonthsOfAge\":132,\"DaysAfterPreviousDose\":null}]}"
                        },
                        new
                        {
                            Id = 3,
                            DaysToDelivery = 15,
                            IsActive = true,
                            Name = "Janssen",
                            VaccineText = "{\"Id\":3000,\"Name\":\"Antigripal\",\"VaccineType\":\"Vector viral\",\"Type\":2,\"Doses\":[{\"Id\":3001,\"Number\":0,\"IsReinforcement\":false,\"MinMonthsOfAge\":0,\"DaysAfterPreviousDose\":365}]}"
                        });
                });

            modelBuilder.Entity("VacunassistBackend.Entities.LocalBatchVaccine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BatchVaccineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DistributionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OverdueQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("Synchronized")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BatchVaccineId");

                    b.ToTable("LocalBatchVaccines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatchVaccineId = 5,
                            DistributionDate = new DateTime(2022, 12, 19, 0, 3, 42, 778, DateTimeKind.Local).AddTicks(7308),
                            OverdueQuantity = 0,
                            Province = "Buenos Aires",
                            Quantity = 600,
                            RemainingQuantity = 600,
                            Synchronized = false
                        });
                });

            modelBuilder.Entity("VacunassistBackend.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Province", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "02",
                            Name = "Ciudad Autónoma de Buenos Aires"
                        },
                        new
                        {
                            Id = 2,
                            Code = "06",
                            Name = "Buenos Aires"
                        },
                        new
                        {
                            Id = 3,
                            Code = "10",
                            Name = "Catamarca"
                        },
                        new
                        {
                            Id = 4,
                            Code = "14",
                            Name = "Córdoba"
                        },
                        new
                        {
                            Id = 5,
                            Code = "18",
                            Name = "Corrientes"
                        },
                        new
                        {
                            Id = 6,
                            Code = "22",
                            Name = "Chaco"
                        },
                        new
                        {
                            Id = 7,
                            Code = "26",
                            Name = "Chubut"
                        },
                        new
                        {
                            Id = 8,
                            Code = "30",
                            Name = "Entre Ríos"
                        },
                        new
                        {
                            Id = 9,
                            Code = "34",
                            Name = "Formosa"
                        },
                        new
                        {
                            Id = 10,
                            Code = "38",
                            Name = "Jujuy"
                        },
                        new
                        {
                            Id = 11,
                            Code = "42",
                            Name = "La Pampa"
                        },
                        new
                        {
                            Id = 12,
                            Code = "46",
                            Name = "La Rioja"
                        },
                        new
                        {
                            Id = 13,
                            Code = "50",
                            Name = "Mendoza"
                        },
                        new
                        {
                            Id = 14,
                            Code = "54",
                            Name = "Misiones"
                        },
                        new
                        {
                            Id = 15,
                            Code = "58",
                            Name = "Neuquén"
                        },
                        new
                        {
                            Id = 16,
                            Code = "62",
                            Name = "Río Negro"
                        },
                        new
                        {
                            Id = 17,
                            Code = "66",
                            Name = "Salta"
                        },
                        new
                        {
                            Id = 18,
                            Code = "70",
                            Name = "San Juan"
                        },
                        new
                        {
                            Id = 19,
                            Code = "74",
                            Name = "San Luis"
                        },
                        new
                        {
                            Id = 20,
                            Code = "78",
                            Name = "Santa Cruz"
                        },
                        new
                        {
                            Id = 21,
                            Code = "82",
                            Name = "Santa Fe"
                        },
                        new
                        {
                            Id = 22,
                            Code = "86",
                            Name = "Santiago del Estero"
                        },
                        new
                        {
                            Id = 23,
                            Code = "90",
                            Name = "Tucumán"
                        },
                        new
                        {
                            Id = 24,
                            Code = "94",
                            Name = "Tierra del Fuego, Antártida e Islas del Atlántico Sur"
                        });
                });

            modelBuilder.Entity("VacunassistBackend.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DeliveredTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DevelopedVaccineId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ETA")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DevelopedVaccineId");

                    b.ToTable("PurchaseOrders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DevelopedVaccineId = 3,
                            PurchaseDate = new DateTime(2022, 12, 19, 0, 3, 42, 778, DateTimeKind.Local).AddTicks(7245),
                            Quantity = 1400,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            DevelopedVaccineId = 3,
                            PurchaseDate = new DateTime(2022, 12, 19, 0, 3, 42, 778, DateTimeKind.Local).AddTicks(7247),
                            Quantity = 1200,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            BatchNumber = "PF1000001",
                            DeliveredTime = new DateTime(2022, 12, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DevelopedVaccineId = 1,
                            ETA = new DateTime(2022, 12, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            PurchaseDate = new DateTime(2022, 11, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Quantity = 800,
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            BatchNumber = "PF1000121",
                            DeliveredTime = new DateTime(2022, 12, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DevelopedVaccineId = 1,
                            ETA = new DateTime(2022, 12, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            PurchaseDate = new DateTime(2022, 11, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Quantity = 400,
                            Status = 2
                        },
                        new
                        {
                            Id = 5,
                            BatchNumber = "R1000001",
                            DeliveredTime = new DateTime(2022, 12, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DevelopedVaccineId = 2,
                            ETA = new DateTime(2022, 12, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            PurchaseDate = new DateTime(2022, 10, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Quantity = 560,
                            Status = 2
                        },
                        new
                        {
                            Id = 6,
                            BatchNumber = "FLU12214001",
                            DeliveredTime = new DateTime(2022, 12, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DevelopedVaccineId = 3,
                            ETA = new DateTime(2022, 12, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            PurchaseDate = new DateTime(2022, 12, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Quantity = 1500,
                            Status = 2
                        },
                        new
                        {
                            Id = 7,
                            BatchNumber = "FLU12214003",
                            DeliveredTime = new DateTime(2022, 12, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DevelopedVaccineId = 3,
                            ETA = new DateTime(2022, 12, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            PurchaseDate = new DateTime(2022, 12, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Quantity = 3600,
                            Status = 2
                        },
                        new
                        {
                            Id = 8,
                            BatchNumber = "FLU13214121",
                            DeliveredTime = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            DevelopedVaccineId = 3,
                            ETA = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            PurchaseDate = new DateTime(2022, 11, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Quantity = 3600,
                            Status = 2
                        });
                });

            modelBuilder.Entity("VacunassistBackend.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("HealthWorker")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pregnant")
                        .HasColumnType("bit");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Calle Falsa 1234, La Plata",
                            BirthDate = new DateTime(2022, 12, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DNI = "11111111",
                            Email = "admin@vacunassist.com",
                            FullName = "Administrador",
                            Gender = "other",
                            HealthWorker = false,
                            IsActive = true,
                            PasswordHash = "1000:7AnBgUrlHfWKOdGx9jBXBs6bUB4coiO1:JJkJrAqRmC6gLVirDszlrinUA0TiImJK",
                            Pregnant = false,
                            Province = "Buenos Aires",
                            Role = "administrator",
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Calle Falsa 2345, La Plata",
                            BirthDate = new DateTime(2022, 12, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DNI = "22345678",
                            Email = "operador1@vacunassist.com",
                            FullName = "Luis Gutierrez",
                            Gender = "male",
                            HealthWorker = false,
                            IsActive = true,
                            PasswordHash = "1000:UHsg6Rbd+QZeVOW7NDOWGA35Yu4EVRDB:WNIbW5JpwvjXgwc/hq39H4crQD6duDDm",
                            Pregnant = false,
                            Province = "Buenos Aires",
                            Role = "operator",
                            UserName = "Operador1"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Calle Falsa 9874, Salta",
                            BirthDate = new DateTime(2022, 12, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DNI = "89785451",
                            Email = "estefania@vacunassist.com",
                            FullName = "Estefania Borzi",
                            Gender = "female",
                            HealthWorker = false,
                            IsActive = true,
                            PasswordHash = "1000:DGSDaj3Ip4tnNAI7Th4sD5blX0jwURCD:/mME0CgrfhPCOdUml9ikK9qs3LINgBH1",
                            Pregnant = false,
                            Province = "Salta",
                            Role = "operator",
                            UserName = "Operador2"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Calle Falsa 9874, Salta",
                            BirthDate = new DateTime(2022, 12, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DNI = "89785451",
                            Email = "jr@vacunassist.com",
                            FullName = "Jose Luis Rodriguez",
                            Gender = "male",
                            HealthWorker = false,
                            IsActive = true,
                            PasswordHash = "1000:SDfkS+pYeZu8hoyD2l6fh9e6dtj8+ZBO:4tSmrea4p9VeTHS9kcnw9v6dt+NMXr+X",
                            Pregnant = false,
                            Province = "Buenos Aires",
                            Role = "analyst",
                            UserName = "Analista1"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Calle Falsa 4567, La Plata",
                            BirthDate = new DateTime(2022, 12, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DNI = "11111111",
                            Email = "vacunador@email.com",
                            FullName = "Vacunador",
                            Gender = "other",
                            HealthWorker = false,
                            IsActive = true,
                            PasswordHash = "1000:Z+JCEgv4au06NiEpWGOXqrBieJ5Krkyz:Af1cP2BzJTFh5dNC2ZOqVrwwXrjpU0nY",
                            Pregnant = false,
                            Province = "Buenos Aires",
                            Role = "vacunator",
                            UserName = "Vacunador"
                        });
                });

            modelBuilder.Entity("VacunnasistBackend.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HealthWorker")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pregnant")
                        .HasColumnType("bit");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("VacunassistBackend.Entities.AppliedVaccine", b =>
                {
                    b.HasOne("VacunassistBackend.Entities.LocalBatchVaccine", "LocalBatchVaccine")
                        .WithMany()
                        .HasForeignKey("LocalBatchVaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VacunnasistBackend.Entities.Patient", "Patient")
                        .WithMany("AppliedVaccines")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VacunassistBackend.Entities.User", "User")
                        .WithMany("Vaccines")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalBatchVaccine");

                    b.Navigation("Patient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VacunassistBackend.Entities.BatchVaccine", b =>
                {
                    b.HasOne("VacunassistBackend.Entities.DevelopedVaccine", "DevelopedVaccine")
                        .WithMany()
                        .HasForeignKey("DevelopedVaccineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VacunassistBackend.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DevelopedVaccine");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("VacunassistBackend.Entities.Department", b =>
                {
                    b.HasOne("VacunassistBackend.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("VacunassistBackend.Entities.LocalBatchVaccine", b =>
                {
                    b.HasOne("VacunassistBackend.Entities.BatchVaccine", "BatchVaccine")
                        .WithMany("Distributions")
                        .HasForeignKey("BatchVaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatchVaccine");
                });

            modelBuilder.Entity("VacunassistBackend.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("VacunassistBackend.Entities.DevelopedVaccine", "DevelopedVaccine")
                        .WithMany()
                        .HasForeignKey("DevelopedVaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DevelopedVaccine");
                });

            modelBuilder.Entity("VacunnasistBackend.Entities.Patient", b =>
                {
                    b.HasOne("VacunassistBackend.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("VacunassistBackend.Entities.BatchVaccine", b =>
                {
                    b.Navigation("Distributions");
                });

            modelBuilder.Entity("VacunassistBackend.Entities.User", b =>
                {
                    b.Navigation("Vaccines");
                });

            modelBuilder.Entity("VacunnasistBackend.Entities.Patient", b =>
                {
                    b.Navigation("AppliedVaccines");
                });
#pragma warning restore 612, 618
        }
    }
}
